### ISSUE TITLE
숫자값을 불러올때, Cannot get a text value from a numeric cell 익셉션이 발생합니다.

### ISSUE THREAD

**Issue by siyoon210** [ckpoint/ToExcel#7]
java.lang.IllegalStateException: Cannot get a text value from a numeric cell

	at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:845)
	at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:294)
	at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:246)
	at com.github.ckpoint.toexcel.util.TitleRowHelper.countMatchTitles(TitleRowHelper.java:65)
	at com.github.ckpoint.toexcel.util.TitleRowHelper.findTitleRow(TitleRowHelper.java:40)
	at com.github.ckpoint.toexcel.core.ToWorkSheet.map(ToWorkSheet.java:157)

---

리드미에 있는 예제를 그대로 따라해보고 있는데 age가 숫자값이면 읽어오질 못합니다.
age에 담긴 값을 문자로 바꾸고 (ex age1, age2 ...) 모델도 String으로 두면 발생하지 않습니다.

**Comment by lhs1553** [comment]
안녕하세요 

해당 문제는, 
타이틀 raw 검색중 발생하는 문제로 확인되었으며, 
0.9.2 버전에 버그 픽스되어 릴리즈 되었습니다. 

관심가져주셔서 진심으로 감사합니다.
